#!/bin/sh
#
# Update the iterm window title to the current directory name.
iterm_title() {
	if [ -n "$ITERM_SESSION_ID" ]; then
		local title=""
		local dev_dir="$HOME/Development"
		local rel_path="${PWD#$dev_dir/}"

		# Check if we are directly in $HOME/Development or in its subdirectories.
		if [[ "$PWD" == "$dev_dir"* ]]; then
			# Extract the first sub-directory name under Development.
			if [[ "$rel_path" == */* ]]; then
				title=${rel_path%%/*}
			else
				title="$(basename "$PWD")"
			fi
		fi

		# If the title is empty, default to the basename of the current directory.
		if [ -z "$title" ]; then
			title="$(basename "$PWD")"
		fi

		# Set the iTerm window title using ANSI escape codes.
		echo -ne "\033]0;$title\007"
	fi
}
