cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'saulpw/vd'             # Used by visidata

brew 'ack'
brew 'bash-completion'
brew 'b2-tools'
brew 'composer'
brew 'coreutils'
brew 'git'
brew 'gcloud'
brew 'grc'                  # Needed for `ls` to work in ZSH apparently?
brew 'imagemagick'
brew 'llm'
brew 'libmemcached'
brew 'mariadb'
brew 'memcached'
brew 'mole'
brew 'ngrok'
brew 'node'
brew 'openssl'
brew 'orbstack'
brew 'python'
brew 'rsync'
brew 'subversion'
brew 'visidata'
brew 'watchman'
brew 'wget'
brew 'z'

cask 'insomnia'
cask 'ghostty'
